import React, { useState } from "react";

export default function RequestForm() {
  // 1. Maintain your form states
  const [formData, setFormData] = useState({
    title: "",
    category: "",
    description: "",
    requestType: "in-person",
    location: "",
    desiredDate: "",
    desiredTime: "",
    flexible: false,
  });

  const [isGenerating, setIsGenerating] = useState(false);

  // 2. Add input change helper
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
  };

  // 3. Add the secure AI generation backend trigger
  const handleAutoGenerateDescription = async () => {
    if (!formData.title || formData.title.trim().length < 5) {
      alert("Please provide a Title (at least 5 characters) first so the AI has context!");
      return;
    }
    if (!formData.category) {
      alert("Please select a Category first!");
      return;
    }

    setIsGenerating(true);

    try {
      const response = await fetch("/requests/api/generate-description", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: formData.title,
          category: formData.category,
        }),
      });

      const data = await response.json();

      if (data.success) {
        // Update the description field in state
        setFormData((prev) => ({
          ...prev,
          description: data.description,
        }));
      } else {
        alert("AI Generation failed: " + data.message);
      }
    } catch (error) {
      console.error("AI Generation Network Error:", error);
      alert("An error occurred while communicating with the server.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="form-box">
      <p className="form-box-title">Request Details</p>

      <form onSubmit={(e) => e.preventDefault()} noValidate>
        {/* Title Input Field */}
        <div className="form-group">
          <label htmlFor="title">Request Title *</label>
          <input
            type="text"
            id="title"
            name="title"
            className="form-control"
            placeholder="e.g., Need help moving furniture"
            value={formData.title}
            onChange={handleChange}
          />
        </div>

        {/* Category Select Input Field */}
        <div className="form-group">
          <label htmlFor="category">Category *</label>
          <select
            id="category"
            name="category"
            className="form-control"
            value={formData.category}
            onChange={handleChange}
          >
            <option value="">Select a category</option>
            {["Home Tasks", "IT Repair", "Gardening", "Tutoring", "Pet Care", "Transportation", "Other"].map((cat) => (
              <option key={cat} value={cat}>{cat}</option>
            ))}
          </select>
        </div>

        {/* Description Textarea Field with AI Button integrated */}
        <div className="form-group">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "6px" }}>
            <label htmlFor="description" style={{ marginBottom: 0 }}>Description *</label>
            
            {/* ✨ AI Auto-generation button */}
            <button
              type="button"
              className="btn-secondary"
              disabled={isGenerating}
              onClick={handleAutoGenerateDescription}
              style={{ padding: "5px 10px", fontSize: "12px", fontWeight: "600", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: "4px" }}
            >
              {isGenerating ? "Thinking... 🧠" : "✨ Auto-Generate with AI"}
            </button>
          </div>

          <textarea
            id="description"
            name="description"
            className="form-control"
            placeholder="Provide detailed information about what you need help with..."
            rows="5"
            value={formData.description}
            onChange={handleChange}
          />
        </div>

        {/* Form Action Controls */}
        <div className="form-actions" style={{ marginTop: "20px" }}>
          <button type="button" className="btn-secondary">Cancel</button>
          <button type="submit" className="btn-primary">Post Request</button>
        </div>
      </form>
    </div>
  );
}